// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZn0070zC7PyHK3w5rYMx2vX6yX8oBRg4',
    appId: '1:378913328811:android:c054115186ed84e781f1ee',
    messagingSenderId: '378913328811',
    projectId: 'helping-hand-project',
    storageBucket: 'helping-hand-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGf6UZV9LmQFeq7ditEpA_R49G32xTbh0',
    appId: '1:378913328811:ios:d1fc96d35216195881f1ee',
    messagingSenderId: '378913328811',
    projectId: 'helping-hand-project',
    storageBucket: 'helping-hand-project.appspot.com',
    iosClientId: '378913328811-4b678skr925u1876kvc33cn7hs7nsmdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpingHand',
  );
}
